services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: escrevabem-app
    volumes:
      - .:/var/www
    environment:
      APP_ENV: production
    working_dir: /var/www
    depends_on:
      - postgres
      - redis
    networks:
      - escrevabem

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: escrevabem-node
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: npm run build
    networks:
      - escrevabem

  nginx:
    image: nginx:stable-alpine
    container_name: escrevabem-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - escrevabem

  postgres:
    image: postgres:15
    container_name: escrevabem-postgres
    environment:
      POSTGRES_DB: escrevabem
      POSTGRES_USER: escreva
      POSTGRES_PASSWORD: bem123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - escrevabem

  redis:
    image: redis:alpine
    container_name: escrevabem-redis
    networks:
      - escrevabem

volumes:
  pgdata:

networks:
  escrevabem:
